service: operationalLambda
app: serverless

custom: ${file(ymls/custom.yml)}
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ${self:custom.region.${self:provider.stage}}

functions:
  - ${file(src/functions/test/index.yml)}

resources:
  - ${file(resources/alarms.yml)}
