service: operationallambda
app: serverless 

custom:

  invocation_threshold: ${opt:invocation_threshold, '10'}
  throttled_count: ${opt:throttled_count, '5'}
  defaultStage: test 
  profiles:
    test: learn 
    dev: bottle
    staging: bottle 
    prod: bottle 

  region: 
    test: us-east-1
    dev: us-east-1
    staging: us-east-1
    prod: us-east-1

    iamRoleStatements:
      - Effect: "Allow"
        Action:
           Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
        Resource:
          - "*"
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: ${self:custom.region.${self:provider.stage}}


functions:
  hello:
    handler: handler.hello
    events:
     - http:
          path: hello
          method: get
          cors: true

resources:
  - ${file(resources/alarms.yml)}

